name: Deploy-To-Azure
run-name: deploy-to-azure

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        run: |
          echo ${{ secrets.AZURE_ACR_PASSWORD }} | docker login ${{ secrets.AZURE_ACR_LOGIN_SERVER }} -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/myapp:${{ github.sha }} .

      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/myapp:${{ github.sha }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name <your-webapp-name> \
            --resource-group <your-resource-group> \
            --docker-custom-image-name ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/myapp:${{ github.sha }} \
            --docker-registry-server-url https://${{ secrets.AZURE_ACR_LOGIN_SERVER }}

      - name: Restart Azure Web App
        run: |
          az webapp restart --name <your-webapp-name> --resource-group <your-resource-group>