name: Deploy-To-Azure
run-name: deploy-to-azure

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        run: |
          docker login pormel.azurecr.io -u pormel -p xJ2/dVoODkqNphVOUjbPwO3NIhvaaElengJUg26xFr+ACRBiFoWk

      - name: Build Docker image
        run: |
          docker build -t pormel.azurecr.io/pormel:test-action .

      - name: Push Docker image to ACR
        run: |
          docker push pormel.azurecr.io/pormel:test-action

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "fdfb88be-4122-4773-b3e8-5b2f51ed480d",
              "clientSecret": "esD8Q~DpQo1-DwDaPPmBJIc5kwBdKbw5eIqYzdkq",
              "subscriptionId": "47874bfe-e8c3-46c9-b7f9-12a98e7e0554",
              "tenantId": "aef7b9dd-3bc2-453e-85e2-86c46aaf68ee",
              "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
              "resourceManagerEndpointUrl": "https://management.azure.com/",
              "activeDirectoryGraphResourceId": "https://graph.windows.net/",
              "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
              "galleryEndpointUrl": "https://gallery.azure.com/",
              "managementEndpointUrl": "https://management.core.windows.net/"
            }

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name pormel-docker \
            --resource-group full \
            --docker-custom-image-name pormel.azurecr.io/pormel:test-action-1.1 \
            --docker-registry-server-url https://pormel.azurecr.io

      - name: Restart Azure Web App
        run: |
          az webapp restart --name pormel-docker --resource-group full