name: Deploy-To-Azure
run-name: deploy-to-azure

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        run: |
          docker login pormel.azurecr.io
        with: 
          - username: pormel
          - password: xJ2/dVoODkqNphVOUjbPwO3NIhvaaElengJUg26xFr+ACRBiFoWk

      - name: Build Docker image
        run: |
          docker build -t pormel.azurecr.io/pormel:test-action .

      - name: Push Docker image to ACR
        run: |
          docker push pormel.azurecr.io/pormel:test-action

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name pormel-docker \
            --resource-group full \
            --docker-custom-image-name pormel.azurecr.io/pormel:test-action \
            --docker-registry-server-url https://pormel.azurecr.io

      - name: Restart Azure Web App
        run: |
          az webapp restart --name pormel-docker --resource-group full